# Generated by Django 3.1.4 on 2020-12-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.TextField(max_length=200)),
                ('programming_language_used', models.TextField(max_length=30)),
                ('project_code_link', models.URLField()),
                ('project_description', models.TextField()),
            ],
        ),
    ]
